### ISSUE TITLE
incompatible with Express 4

### ISSUE THREAD

**Issue by weisjohn** [davglass/express-session-mongo#22]
trying to use with Express 4, I get:

```
Error: Most middleware (like session) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.
    at Function.Object.defineProperty.get ([..redacted..]/node_modules/express/lib/express.js:89:13)
    at Object.<anonymous> ([..redacted..]/node_modules/express-session-mongo/lib/express-session-mongo.js:8:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Object..js (/Users/jweis/.nvm/v0.10.26/lib/node_modules/node-dev/lib/hook.js:52:17)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> ([..redacted..]/sessions.js:4:18)
```

**Comment by MaffooBristol** [comment]
:+1: to get this pulled!

**Comment by MaffooBristol** [comment]
Thanks davglass :)
